criaCartao(
    'PROGRAMAÇÃO',
    'O QUE É UM ALGORITMO NA PROGRAMAÇÃO?',
    'É UM CONJUNTO DE INSTRUÇÕES QUE DEFINE O SEQUENCIAMENTO DE PASSOS PARA QUE UM COMPUTADOR EXECUTE UMA TAREFA OU RESOLVA UM PROBLEMA.'
)

criaCartao(
    'MATEMÁTICA',
    'O QUE É UM NÚMERO REAL?',
    'UM NÚMERO REAL É UM CONJUNTO NUMÉRICO FORMADO POR QUALQUER NÚMERO INTEIRO OU DECIMAL.'
)

criaCartao(
    'QUÍMICA',
    'O QUE É UMA SOLUÇÃO NA QUÍMICA?',
    'SOLUÇÕES SÃO SISTEMAS HOMOGÊNEOS FORMADOS PELA MISTURA DE DUAS OU MAIS SUBSTÂNCIAS.'
)

criaCartao(
    'Lingua inglesa',
    'Como se diz oi em Inglês?',
    'Oi em ingles é HI (RAI)'
)
