criaCartao(
    'PROGRAMAÇÃO',
    'O QUE É UM ALGORITMO NA PROGRAMAÇÃO?',
    'É UM CONJUNTO DE INSTRUÇÕES QUE DEFINE O SEQUENCIAMENTO DE PASSOS PARA QUE UM COMPUTADOR EXECUTE UMA TAREFA OU RESOLVA UM PROBLEMA.'
)

criaCartao(
    'MATEMÁTICA',
    'O QUE É UM NÚMERO REAL?',
    'UM NÚMERO REAL É UM CONJUNTO NUMÉRICO FORMADO POR QUALQUER NÚMERO INTEIRO OU DECIMAL.'
)

criaCartao(
    'QUÍMICA',
    'O QUE É UMA SOLUÇÃO NA QUÍMICA?',
    'SOLUÇÕES SÃO SISTEMAS HOMOGÊNEOS FORMADOS PELA MISTURA DE DUAS OU MAIS SUBSTÂNCIAS.'
)

criaCartao(
    'FÍSICA',
    'O QUE É ELETROMAGNETISMO?',
    'É UMA ÁREA DE ESTUDO DA FÍSICA QUE ANALISA OS FENÔMENOS ELÉTRICOS E OS FENÔMENOS MAGNÉTICOS DE MANEIRA UNIFICADA.'
)

criaCartao(
    'BIOLOGIA',
    'O QUE É CADEIA ALIMENTAR?',
    'REPRESENTA UMA SEQUÊNCIA DE SERES VIVOS NA QUAL UM ORGANISMO SERVE DE ALIMENTO PARA OUTRO.'
)
criaCartao(
    'ECONOMIA',
    'O QUE SÃO AÇÕES NA ECONOMIA?',
    'SÃO TÍTULOS QUE REPRESENTAM UMA FRAÇÃO DO CAPITAL DE UMA EMPRESA, E TEM COMO OBJETIVO CAPTAR RECURSOS.'
)
